version: "3.8"

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    user: "${PUID:-1000}:${PGID:-1000}"
    env_file:
      # Use temp env from startup.sh if provided, else fallback to repo file
      - ${COMPOSE_ENV_FILE:-./settings.env}
    volumes:
      - ./data/bwdata:/data:rw
    networks:
      - bw_net
    healthcheck:
      # Enhanced: Support both curl and wget for different VaultWarden images
      test: ["CMD-SHELL", "(command -v curl >/dev/null 2>&1 && curl -fsS http://127.0.0.1:80/alive) || (command -v wget >/dev/null 2>&1 && wget -qO- http://127.0.0.1:80/alive) || exit 1"]
      interval: 5m
      timeout: 15s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.35'  # Optimized for 1.0 CPU total
        reservations:
          memory: 128M
          cpus: '0.175'
    environment:
      # Standardized: Use consistent environment variables
      - DATABASE_URL=${DATABASE_URL:-sqlite:////data/bwdata/db.sqlite3}
      - ROCKET_WORKERS=${ROCKET_WORKERS:-1}
      - WEBSOCKET_ENABLED=${WEBSOCKET_ENABLED:-false}
      - EXTENDED_LOGGING=${EXTENDED_LOGGING:-true}
      - LOG_LEVEL=${LOG_LEVEL:-warn}
      # Additional VaultWarden configuration
      - ADMIN_TOKEN=${ADMIN_TOKEN:-}
      - SIGNUPS_ALLOWED=${SIGNUPS_ALLOWED:-false}
      - INVITES_ALLOWED=${INVITES_ALLOWED:-true}
      - WEB_VAULT_ENABLED=${WEB_VAULT_ENABLED:-true}
      - SHOW_PASSWORD_HINTS=${SHOW_PASSWORD_HINTS:-false}
      - DISABLE_2FA_REMEMBER=${DISABLE_2FA_REMEMBER:-false}
      # SMTP Configuration
      - SMTP_HOST=${SMTP_HOST:-}
      - SMTP_FROM=${SMTP_FROM:-}
      - SMTP_FROM_NAME=${SMTP_FROM_NAME:-}
      - SMTP_USERNAME=${SMTP_USERNAME:-}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-}
      - SMTP_SECURITY=${SMTP_SECURITY:-starttls}
      - SMTP_PORT=${SMTP_PORT:-587}
      # Push Notifications
      - PUSH_ENABLED=${PUSH_ENABLED:-true}
      - PUSH_INSTALLATION_ID=${PUSH_INSTALLATION_ID:-}
      - PUSH_INSTALLATION_KEY=${PUSH_INSTALLATION_KEY:-}
      - PUSH_RELAY_URI=${PUSH_RELAY_URI:-https://push.bitwarden.com}
      # Domain Configuration
      - DOMAIN=${DOMAIN:-}
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
        labels: "service=vaultwarden"

  bw_caddy:
    image: caddy:2-alpine
    container_name: bw_caddy
    restart: unless-stopped
    user: "${PUID:-1000}:${PGID:-1000}"
    env_file:
      - ${COMPOSE_ENV_FILE:-./settings.env}
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./data/caddy_data:/data
      - ./data/caddy_config:/config
      - ./data/caddy_logs:/logs
      - ./caddy/cloudflare_ips.caddy:/etc/caddy/cloudflare_ips.caddy:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      vaultwarden:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "caddy validate --config /etc/caddy/Caddyfile || exit 1"]
      interval: 10m
      timeout: 15s
      retries: 3
      start_period: 45s
    networks:
      - bw_net
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.12'  # Optimized for 1.0 CPU total
        reservations:
          memory: 64M
          cpus: '0.06'
    environment:
      # Caddy-specific environment variables
      - CADDY_ADMIN=${CADDY_ADMIN:-off}
      - ADMIN_EMAIL=${ADMIN_EMAIL:-}
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
        labels: "service=caddy"

  bw_fail2ban:
    image: lscr.io/linuxserver/fail2ban:latest
    container_name: bw_fail2ban
    restart: unless-stopped
    env_file:
      - ${COMPOSE_ENV_FILE:-./settings.env}
    volumes:
      - ./fail2ban/jail.d/jail.local:/config/jail.local:ro
      - ./fail2ban/filter.d:/config/filter.d:ro
      - ./caddy/cloudflare_ips.txt:/config/cloudflare_ips.txt:ro
      - ./data/caddy_logs:/logs/caddy:ro
      - ./data/bwdata:/logs/vaultwarden:ro
      - ./data/fail2ban:/config:rw
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - VERBOSITY=-vv
      # Fail2ban configuration from environment
      - TZ=${TZ:-UTC}
    healthcheck:
      test: ["CMD-SHELL", "fail2ban-client ping >/dev/null 2>&1 || exit 1"]
      interval: 15m
      timeout: 15s
      retries: 3
      start_period: 90s
    networks:
      - bw_net
    depends_on:
      bw_caddy:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 64M
          cpus: '0.08'
        reservations:
          memory: 32M
          cpus: '0.04'
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
        labels: "service=fail2ban"
    profiles:
      - security

  bw_ddclient:
    image: lscr.io/linuxserver/ddclient:latest
    container_name: bw_ddclient
    restart: unless-stopped
    env_file:
      - ${COMPOSE_ENV_FILE:-./settings.env}
    volumes:
      - ./ddclient:/config:rw
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f ddclient >/dev/null || exit 1"]
      interval: 60m
      timeout: 15s
      retries: 2
      start_period: 60s
    networks:
      - bw_net
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
      # DDClient configuration from environment
      - DDCLIENT_PROTOCOL=${DDCLIENT_PROTOCOL:-}
      - DDCLIENT_LOGIN=${DDCLIENT_LOGIN:-}
      - DDCLIENT_PASSWORD=${DDCLIENT_PASSWORD:-}
      - DDCLIENT_ZONE=${DDCLIENT_ZONE:-}
      - DDCLIENT_HOST=${DDCLIENT_HOST:-}
    deploy:
      resources:
        limits:
          memory: 32M
          cpus: '0.05'
        reservations:
          memory: 16M
          cpus: '0.025'
    logging:
      driver: "json-file"
      options:
        max-size: "25m"
        max-file: "2"
        labels: "service=ddclient"
    profiles:
      - dns

  bw_backup:
    build:
      context: ./backup
      dockerfile: Dockerfile
    image: bitwarden_sqlite_backup:latest
    container_name: bw_backup
    restart: unless-stopped
    user: "${PUID:-1000}:${PGID:-1000}"
    env_file:
      - ${COMPOSE_ENV_FILE:-./settings.env}
    volumes:
      - ./data/backups:/backups:rw
      - ./data/backup_logs:/var/log/backup:rw
      - ./backup/config:/home/backup/.config/rclone:rw
      - ./data/bwdata:/data/bwdata:ro
    networks:
      - bw_net
    depends_on:
      vaultwarden:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "pgrep crond >/dev/null && test -w /backups || exit 1"]
      interval: 60m
      timeout: 15s
      retries: 3
      start_period: 120s
    environment:
      # Standardized: Use consistent paths and environment variables
      - BACKUP_DIR=/backups
      - LOG_DIR=/var/log/backup
      - RETENTION_DAYS=${BACKUP_RETENTION_DAYS:-30}
      - BACKUP_PASSPHRASE=${BACKUP_PASSPHRASE:-}
      - BACKUP_REMOTE=${BACKUP_REMOTE:-}
      - BACKUP_PATH=${BACKUP_PATH:-vaultwarden-backups}
      - BACKUP_EMAIL=${BACKUP_EMAIL:-}
      - DATABASE_TYPE=sqlite
      # Standardized paths - consistent with settings.env
      - SQLITE_DB_PATH=/data/bwdata/db.sqlite3
      - VAULTWARDEN_DATA_DIR=/data/bwdata
      # Additional backup configuration
      - BACKUP_SCHEDULE=${BACKUP_SCHEDULE:-0 2 * * *}
      - BACKUP_COMPRESS=${BACKUP_COMPRESS:-true}
      - BACKUP_ENCRYPT=${BACKUP_ENCRYPT:-true}
      - BACKUP_VERIFICATION=${BACKUP_VERIFICATION:-true}
      - BACKUP_NOTIFY=${BACKUP_NOTIFY:-true}
      - BACKUP_NOTIFY_ON=${BACKUP_NOTIFY_ON:-all}
      - RCLONE_TRANSFER_TIMEOUT=${RCLONE_TRANSFER_TIMEOUT:-30m}
      - RCLONE_RETRIES=${RCLONE_RETRIES:-3}
      - TZ=${TZ:-UTC}
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.30'  # Optimized for 1.0 CPU total
        reservations:
          memory: 64M
          cpus: '0.15'
    profiles:
      - backup
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
        labels: "service=sqlite-backup"

  bw_watchtower:
    image: containrrr/watchtower:latest
    restart: unless-stopped
    container_name: bw_watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=${WATCHTOWER_SCHEDULE:-0 0 3 * * 0}
      - TZ=${TZ:-UTC}
      - WATCHTOWER_NOTIFICATIONS_LEVEL=info
      - WATCHTOWER_INCLUDE_STOPPED=false
      - WATCHTOWER_REVIVE_STOPPED=false
      - WATCHTOWER_LABEL_ENABLE=true
      # Additional watchtower configuration
      - WATCHTOWER_NOTIFICATIONS=${WATCHTOWER_NOTIFICATIONS:-false}
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=${SMTP_FROM:-}
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=${ALERT_EMAIL:-}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=${SMTP_HOST:-}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=${SMTP_PORT:-587}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=${SMTP_USERNAME:-}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${SMTP_PASSWORD:-}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - bw_net
    deploy:
      resources:
        limits:
          memory: 64M
          cpus: '0.10'  # Optimized for 1.0 CPU total
        reservations:
          memory: 32M
          cpus: '0.05'
    logging:
      driver: "json-file"
      options:
        max-size: "25m"
        max-file: "2"
        labels: "service=watchtower"
    profiles:
      - maintenance

networks:
  bw_net:
    driver: bridge
    name: vaultwarden_network

# ==============================================
# VaultWarden-OCI-Slim SQLite Configuration
# Optimized for 1 OCPU/6GB OCI A1 Flex
# ==============================================
# 
# Resource Allocation Summary:
# - VaultWarden: 0.35 CPU, 256MB RAM
# - Caddy:       0.12 CPU, 128MB RAM  
# - Fail2ban:    0.08 CPU, 64MB RAM
# - Backup:      0.30 CPU, 128MB RAM
# - Watchtower:  0.10 CPU, 64MB RAM
# - DDClient:    0.05 CPU, 32MB RAM
# Total:         1.00 CPU, 672MB RAM
#
# Key Optimizations:
# ✓ Removed MariaDB container (saves 0.5 CPU, 1GB RAM)
# ✓ Removed Redis container (saves 0.25 CPU, 256MB RAM)
# ✓ Removed logrotate container (saves 0.1 CPU, 32MB RAM)
# ✓ SQLite database (file-based, no server overhead)
# ✓ Single worker process (ROCKET_WORKERS=1)
# ✓ WebSocket disabled (polling mode for efficiency)
# ✓ Robust healthchecks supporting different VaultWarden images
# ✓ Comprehensive environment variable configuration
# ✓ Standardized paths across all services
# ✓ Enhanced service configuration management
#
# Profile Usage Examples:
# docker compose up -d                           # Core services only
# docker compose --profile backup up -d         # Core + backup
# docker compose --profile security up -d       # Core + fail2ban  
# docker compose --profile dns up -d            # Core + ddclient
# docker compose --profile maintenance up -d    # Core + watchtower
# ./startup.sh                                  # Automatic profile selection
#
# Enhancements Applied:
# ✓ Standardized environment variable usage across all services
# ✓ Added comprehensive VaultWarden configuration via env vars
# ✓ Enhanced backup service with all configuration options
# ✓ Improved Watchtower with email notification support
# ✓ Added DDClient environment variable configuration
# ✓ Consistent path references for SQLite database
# ✓ Enhanced logging configuration for all services
# ✓ Improved volume mount specifications
# ✓ Added timezone configuration to all relevant services
